### ISSUE TITLE
Save patch?

### ISSUE THREAD

**Issue by noctis90210** [enler/PokemonTypingDSHacking#1]
Hello, this is really not an issue, i have a link below for some patch code, these are AP fix and onscreen keyboard, but no patch to allow saving... Can i ask for saving patch only? Thanks and have a nice day...

6085 - Learn with Pokemon - Typing Adventure (E)
0000547C: 00 28 F5 D0 → 00 28 C0 46
00004560: DF B5 2A FC FC 0E EF B7 C8 1D DE 8E 7F 95 6A 27 → 1F 40 2D E9 24 00 8F E2 00 10 90 E5 01 00 51 E3
00004570: 2B 11 9A BC 38 10 E0 CD F1 00 18 14 75 91 0A 32 → 1F 80 BD 08 00 20 91 E5 04 30 90 E5 03 00 52 E1
00004580: 25 56 F0 39 AA F7 17 EB 00 84 69 45 DA F6 17 27 → 08 40 90 05 00 40 81 05 0C 00 80 E2 F5 FF FF EA
00004590: D3 26 00 56 40 8D 71 9B B9 66 0C BF 11 3B 50 47 → 48 7C 0F 02 81 AF 00 00 83 A8 00 00 F4 83 0F 02
000045A0: F9 80 C1 F8 94 4F 36 65 6F 57 46 72 B4 C0 2E 23 → 75 B9 00 00 27 C1 00 00 98 54 10 02 79 51 10 02
000045B0: DB 3D FE 86 33 3E E9 9A 00 22 05 DF 70 47 97 57 → 2D 16 00 02 30 C0 10 02 11 BD 10 02 2D 16 00 02
000045C0: 08 70 5C 50 37 6E C2 ED 18 97 C7 D9 8E BD DF 68 → B4 22 10 02 95 1F 10 02 2D 16 00 02 D0 22 10 02
000045D0: AC AE 2B 90 18 9E F0 63 86 2D 70 41 18 B0 B4 AD → F9 1F 10 02 2D 16 00 02 58 C0 10 02 25 BE 10 02
000045E0: 71 46 B3 E8 C8 5E E0 DD → 2D 16 00 02 01 00 00 00
000049F8: 1E FF 2F E1 → D8 FE FF EA
0004870e: 11 43 21 63 →  00 21 21 63

**Comment by enler** [comment]
Oh, sorry, I'm so busy during these days, but my code was written by C, I will try to convert the code to hex-style as soon as possible.

**Comment by enler** [comment]
In fact, you can use the full hack patch(including ap fix and save fix), the patch is used for simulation too, in usual, the wifi keyboard is disabled.
And, save-fixing code written by C is here:
https://github.com/enler/PokemonTypingDSHacking/blob/master/WirelessKeyboard/JPN/arm9/source/backup.c

**Comment by noctis90210** [comment]
Thanks, anyway this is the link on where i found the patches, it says:

Anti-piracy (AP):
Black Screens - Fixed in 1.0 patch
White Screens - Fixed in 1.0 patch
Saving (not yet working)
Wireless keyboard failure - Fixed in 1.0 patch

I tried to play the game with this patch in which no black/white screens and wireless keyboard failure.
Then i can use the onscreen keyboard with that patch.
What's really missing is the ability to save.

Hope you can make another version of this patch, a minimal patch, what i mean is no more black/white screen, enable saving and use the onscreen keyboard (instead the pc keyboard, for portability purposes, we can still play the game even without the large keyboard.

And about the C programing, sorry to say but i have zero idea on how to use that.
Thats why i will be waiting for your hex patches. 😊 Have a nice day...

**Comment by enler** [comment]
@noctis90210 I think making a small patch is unnecessary ,for default the wifi keyboard is disabled, you can use the screen keyboard as usual with the released patch.

**Comment by noctis90210** [comment]
Oh, thas goog to hear, sorry if i didnt test the patch before asking such question. But anyway, nice to hear that onscreen keyboard is also working. I just thought before that the patch is mandatory for external keyboard only... Thanks.
